### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException in JRE 10

### ISSUE THREAD

**Issue by ultradr3mer** [itplr-kosit/validator#11]
When i try to run the given example i get this exception:

> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
>         at de.kosit.validationtool.impl.DefaultCheck.<init>(DefaultCheck.java:73)
>         at de.kosit.validationtool.cmd.InternalCheck.<init>(InternalCheck.java:48)
>         at de.kosit.validationtool.cmd.CommandLineApplication.processActions(CommandLineApplication.java:135)
>         at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:105)
>         at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:85)

I need to add "--add-modules java.xml.bind" like the following to make it run:
>java --add-modules java.xml.bind -jar validationtool-1.0.1-standalone.jar -s scenarios.xml invoice.xml

It would be nice if that was mentioned somehow in the documentation.

**Comment by fbuettner-hb** [comment]
@rkottmann Kümmerst Du Dich darum?

**Comment by pgundlach** [comment]
With Java 11 this workaround seems to break:


```
$ java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

$ java --add-modules java.xml.bind -jar ....

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at de.kosit.validationtool.impl.DefaultCheck.<init>(DefaultCheck.java:73)
	at de.kosit.validationtool.cmd.InternalCheck.<init>(InternalCheck.java:48)
	at de.kosit.validationtool.cmd.CommandLineApplication.processActions(CommandLineApplication.java:135)
	at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:105)
	at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:85)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

This is MacOS 10.14.2

See also https://stackoverflow.com/q/43574426

**Comment by apenski** [comment]
jdk 11 support is planned for the next release, but this is not expected before end of march.

**Comment by apenski** [comment]
we won't support jdk 10, but everything from jdk 11 upward. This is implemented and will be shipped with the next release
