### ISSUE TITLE
Check result to stdout causes an exception

### ISSUE THREAD

**Issue by thomas-cito** [itplr-kosit/validator#131]
Hi together,

I am checking a xRechnung 2.2 with the validator-configuration-xrechnung_2.2.0_2022-11-15. I would like to print the check result via the `-p` option and am getting an exception:

Command:
`java -jar validationtool-1.5.0-standalone.jar -s repo22/scenarios.xml -r repo22 20240423_Test_mit_Container_k1.xml -X -p `

Exception:

```
KoSIT Validator version 1.5.0
Loading scenarios from  file:///home/boskg.local/loeffler/WorkDirs/kositvalidator/repo22/scenarios.xml
Using repository  file:///home/boskg.local/loeffler/WorkDirs/kositvalidator/repo22/

2024-04-26 14:30:20 [INFO] Using resolving strategy STRICT_RELATIVE
2024-04-26 14:30:20 [DEBUG] Try to disable extern DTD access
2024-04-26 14:30:20 [DEBUG] Try to disable extern DTD access
2024-04-26 14:30:20 [INFO] Loading scenarios from file:///home/boskg.local/loeffler/WorkDirs/kositvalidator/repo22/scenarios.xml
2024-04-26 14:30:20 [INFO] Loading scenario content from file:///home/boskg.local/loeffler/WorkDirs/kositvalidator/repo22/
2024-04-26 14:30:21 [INFO] Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung/2.2.0/xsl/XRechnung-UBL-validation-Invoice.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung/2.2.0/xsl/XRechnung-UBL-validation-Invoice.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung/2.2.0/xsl/XRechnung-UBL-validation-CreditNote.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/cii/16b/xsl/EN16931-CII-validation.xsl
2024-04-26 14:30:22 [INFO] Loading XSLT script from  resources/xrechnung/2.2.0/xsl/XRechnung-CII-validation.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/cii/16b/xsl/EN16931-CII-validation.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/xrechnung/2.2.0/xsl/XRechnung-CII-validation.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/cii/16b/xsl/EN16931-CII-validation.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/xrechnung-report.xsl
2024-04-26 14:30:23 [INFO] Loading XSLT script from  resources/default-report.xsl
Loaded "Validator Configuration XRechnung 2.2.0" by Coordination Office for IT Standards (KoSIT) from 2022-11-16 
The following scenarios are available:
  * EN16931 XRechnung (UBL Invoice)
  * EN16931 XRechnung Extension (UBL Invoice)
  * EN16931 XRechnung (UBL CreditNote)
  * EN16931 XRechnung (CII)
  * EN16931 XRechnung Extension (CII)
  * EN16931 (UBL Invoice)
  * EN16931 (UBL CreditNote)
  * EN16931 (CII)

2024-04-26 14:30:24 [INFO] Loaded scenarios for Validator Configuration XRechnung 2.2.0 by Coordination Office for IT Standards (KoSIT) from 2022-11-16.
2024-04-26 14:30:24 [INFO] The following scenarios are available:
EN16931 XRechnung (UBL Invoice)
EN16931 XRechnung Extension (UBL Invoice)
EN16931 XRechnung (UBL CreditNote)
EN16931 XRechnung (CII)
EN16931 XRechnung Extension (CII)
EN16931 (UBL Invoice)
EN16931 (UBL CreditNote)
EN16931 (CII)

2024-04-26 14:30:24 [DEBUG] Try to disable extern DTD access
2024-04-26 14:30:24 [INFO] Setup completed in 3959ms


Processing of 1 objects started
2024-04-26 14:30:24 [INFO] Checking content of /home/boskg.local/loeffler/WorkDirs/kositvalidator/20240423_Test_mit_Container_k1.xml
2024-04-26 14:30:24 [DEBUG] Step DocumentParseAction finished in 3ms
2024-04-26 14:30:24 [DEBUG] Step CreateDocumentIdentificationAction finished in 0ms
2024-04-26 14:30:24 [INFO] No valid scenario configuration found for /home/boskg.local/loeffler/WorkDirs/kositvalidator/20240423_Test_mit_Container_k1.xml
2024-04-26 14:30:24 [DEBUG] Step ScenarioSelectionAction finished in 23ms
2024-04-26 14:30:24 [DEBUG] Step SchemaValidationAction finished in 0ms
2024-04-26 14:30:24 [DEBUG] Step SchematronValidationAction finished in 0ms
2024-04-26 14:30:24 [DEBUG] Step ValidateReportInputAction finished in 70ms
2024-04-26 14:30:24 [DEBUG] Step CreateReportAction finished in 123ms
2024-04-26 14:30:24 [DEBUG] Step ComputeAcceptanceAction finished in 0ms
2024-04-26 14:30:24 [INFO] Serializing result to /home/boskg.local/loeffler/WorkDirs/kositvalidator/./20240423_Test_mit_Container_k1-report.xml
2024-04-26 14:30:24 [DEBUG] Step SerializeReportAction finished in 48ms
java.lang.IllegalArgumentException: can't parse argument number: 
          font-family: Calibri;
          width: 230mm;
        
	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1451)
	at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:491)
	at java.base/java.text.MessageFormat.<init>(MessageFormat.java:390)
	at de.kosit.validationtool.impl.Printer.writeOut(Printer.java:41)
	at de.kosit.validationtool.cmd.PrintReportAction.check(PrintReportAction.java:48)
	at de.kosit.validationtool.impl.DefaultCheck.runCheckInternal(DefaultCheck.java:125)
	at de.kosit.validationtool.cmd.InternalCheck.checkInput(InternalCheck.java:123)
	at de.kosit.validationtool.cmd.Validator.processActions(Validator.java:163)
	at de.kosit.validationtool.cmd.Validator.mainProgram(Validator.java:87)
	at de.kosit.validationtool.cmd.CommandLineOptions.call(CommandLineOptions.java:173)
	at de.kosit.validationtool.cmd.CommandLineOptions.call(CommandLineOptions.java:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:82)
	at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:54)
Caused by: java.lang.NumberFormatException: For input string: "
          font-family: Calibri;
          width: 230mm;
        "
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:638)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at java.base/java.text.MessageFormat.makeFormat(MessageFormat.java:1449)
	... 20 more
cant parse argument number: 
          font-family: Calibri;
          width: 230mm;
        
2024-04-26 14:30:24 [ERROR] can't parse argument number: 
          font-family: Calibri;
          width: 230mm;
```

Without `-p` I am getting a valid result.

Thanks, kind regards

**Comment by hvbtup** [comment]
Same here with `validationtool-1.5.0-standalone.jar`,

**Comment by phax** [comment]
Part of Release v1.5.2 from https://github.com/itplr-kosit/validator/releases/tag/v1.5.2
