### ISSUE TITLE
Unable to run deamon from commandline

### ISSUE THREAD

**Issue by landrix** [itplr-kosit/validator#137]
Hi, I can't start the validator as a daemon. what's wrong?

IMPLEMENTOR="Eclipse Adoptium"
IMPLEMENTOR_VERSION="Temurin-17.0.6+10"
JAVA_VERSION="17.0.6"
JAVA_VERSION_DATE="2023-01-17"

>.\java\bin\java.exe -jar .\validator\validationtool-1.5.0-java8-standalone.jar -s .\validator-configuration30x\scenarios.xml -r .\validator-configuration30x -D -X

KoSIT Validator version 1.5.0
Loading scenarios from  file:///D:/..../Distribution/./validator-configuration30x/scenarios.xml
Using repository  file:///D:/..../Distribution/./validator-configuration30x/

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
        at de.kosit.validationtool.api.Configuration.load(Configuration.java:113)
        at de.kosit.validationtool.cmd.Validator.lambda$getConfiguration$0(Validator.java:196)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at de.kosit.validationtool.cmd.Validator.getConfiguration(Validator.java:200)
        at de.kosit.validationtool.cmd.Validator.startDaemonMode(Validator.java:122)
        at de.kosit.validationtool.cmd.Validator.mainProgram(Validator.java:84)
        at de.kosit.validationtool.cmd.CommandLineOptions.call(CommandLineOptions.java:173)
        at de.kosit.validationtool.cmd.CommandLineOptions.call(CommandLineOptions.java:40)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:82)
        at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:54)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 24 more

**Comment by DavidBal** [comment]
Hi @landrix,

i had the same problem a while back for me useing the `validationtool-1.5.0-standalone.jar` did the trick.

Regards,
David

**Comment by landrix** [comment]
thanks, that works
