### ISSUE TITLE
ANSI encoding of app-info.properties causes a maven exception on pom.xml in Eclipse IDE

### ISSUE THREAD

**Issue by mabiste** [itplr-kosit/validator#146]
I've used the newest Eclipse IDE for Java EE developers (2024-9), but still getting the following problem on pom.xml when checking out the validator project:
> Failed to execute mojo org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources {execution: default-resources} (org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources:default-resources:process-resources)

The complete stack trcace:

> Failed to execute mojo org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources {execution: default-resources} (org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources:default-resources:process-resources)
> 
> org.eclipse.core.runtime.CoreException: Failed to execute mojo org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources {execution: default-resources}
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:404)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$2(MavenExecutionContext.java:355)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:354)
> 	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$2(MavenBuilderImpl.java:159)
> 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:987)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:139)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:292)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
> 	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: org.apache.maven.plugin.MojoExecutionException: filtering C:\Entwicklung\git\validator\src\main\resources\app-info.properties to C:\Entwicklung\git\validator\target\classes\app-info.properties failed with MalformedInputException
> 	at org.apache.maven.plugins.resources.ResourcesMojo.execute(ResourcesMojo.java:347)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:402)
> 	... 32 more
> Caused by: org.apache.maven.shared.filtering.MavenFilteringException: filtering C:\Entwicklung\git\validator\src\main\resources\app-info.properties to C:\Entwicklung\git\validator\target\classes\app-info.properties failed with MalformedInputException
> 	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:116)
> 	at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:268)
> 	at org.apache.maven.plugins.resources.ResourcesMojo.execute(ResourcesMojo.java:343)
> 	... 34 more
> Caused by: java.nio.charset.MalformedInputException: Input length = 1
> 	at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:279)
> 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:405)
> 	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
> 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
> 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:190)
> 	at java.base/java.io.BufferedReader.read1(BufferedReader.java:223)
> 	at java.base/java.io.BufferedReader.implRead(BufferedReader.java:314)
> 	at java.base/java.io.BufferedReader.read(BufferedReader.java:296)
> 	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
> 	at java.base/java.io.BufferedReader.implRead(BufferedReader.java:196)
> 	at java.base/java.io.BufferedReader.read(BufferedReader.java:187)
> 	at org.apache.maven.shared.filtering.BoundedReader.read(BoundedReader.java:71)
> 	at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:209)
> 	at org.apache.maven.shared.filtering.MultiDelimiterInterpolatorFilterReaderLineEnding.read(MultiDelimiterInterpolatorFilterReaderLineEnding.java:179)
> 	at java.base/java.io.Reader.read(Reader.java:269)
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1432)
> 	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1411)
> 	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1208)
> 	at org.apache.maven.shared.filtering.FilteringUtils.copyFile(FilteringUtils.java:332)
> 	at org.apache.maven.shared.filtering.DefaultMavenFileFilter.copyFile(DefaultMavenFileFilter.java:104)
> 	... 36 more

I've found the file name 'app-info.properties' on the stack trace and searched for the root cause ('java.nio.charset.MalformedInputException: Input length = 1'). I've found some hints that the encoding of the file can cause this error.
After converting the encoding of the file from ANSI to UTF-8 (using Notepad++) on my local cloned git repsitory and Eclipse restart / project cleanup, the eror gone away...

**Comment by phax** [comment]
This has been fixed for the 1.5.2 release
