### ISSUE TITLE
Validator runs out of memory when processing multiple large files - memory leak?

### ISSUE THREAD

**Issue by fbuettner-hb** [itplr-kosit/validator#19]
When processing multiple larger input files (> 10m), processing gets slower and slower with each file and finally runs into an out of memory exception. 

That should not be the case, as there should be no need to keep any significant amount of data of a previous input or output when processing the next one.

Original stdout:

```
D:\pk32_test\pk32\Ci\sv>run10mxmx512mall

D:\pk32_test\pk32\Ci\sv>"d:\pk32_test\pk32\CI\bin\java.exe" -classpath bin -Xmx512M -jar d:/pk32_test/pk32/CI/sv/lib/validationtool-1.0.1-standalone.jar -s D:/pk32_test/pk32/Ci/sv/scenarios.xml -o out -h in/*.xml
[main] INFO de.kosit.validationtool.api.CheckConfiguration - Creating default scenario repository (alongside scenario definition)
[main] INFO de.kosit.validationtool.impl.ScenarioRepository - Loading scenarios from file:///D:/pk32_test/pk32/Ci/sv/scenarios.xml
[main] INFO de.kosit.validationtool.impl.ContentRepository - Load schema from source file:/D:/pk32_test/pk32/Ci/sv/lib/validationtool-1.0.1-standalone.jar!/xsd/scenarios.xsd
[main] INFO de.kosit.validationtool.impl.ScenarioRepository - Loaded scenarios for Prüftool-Konfiguration für XGewerbeanzeige by KoSIT from 2018-11-28. The following scenarios are available:

XGewerbeanzeige 1.2 DATML/RAW
XGewerbeanzeige 1.3 DATML/RAW
XGewerbeanzeige 2.0

[main] INFO de.kosit.validationtool.impl.ScenarioRepository - Loading scenario content from file:/D:/pk32_test/pk32/Ci/sv/
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/xgewerbeanzeige-1.2/00041740059999000001.xsl
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/default-report.xsl
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/xgewerbeanzeige-1.3/00041840059999000001.xsl
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/default-report.xsl
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/xgewerbeanzeige-2.0/spezifikation.xsl
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/default-report.xsl
[main] INFO de.kosit.validationtool.impl.ContentRepository - Loading XSLT script from  resources/default-report.xsl
[main] INFO de.kosit.validationtool.cmd.CommandLineApplication - Setup completed in 11343ms

[main] INFO de.kosit.validationtool.impl.DefaultCheck - Checking content of in\ele_20181127132744.xml
[main] INFO de.kosit.validationtool.cmd.ExtractHtmlContentAction - Writing report html 'ele_20181127132744-report' to D:\pk32_test\pk32\Ci\sv\out\ele_20181127132744-report.html
[main] INFO de.kosit.validationtool.cmd.SerializeReportAction - Serializing result to D:\pk32_test\pk32\Ci\sv\out\ele_20181127132744-report.xml
[main] INFO de.kosit.validationtool.impl.DefaultCheck - Finished check of in\ele_20181127132744.xml in 27172ms

[main] INFO de.kosit.validationtool.impl.DefaultCheck - Checking content of in\ele_20181127133238.xml
[main] INFO de.kosit.validationtool.cmd.ExtractHtmlContentAction - Writing report html 'ele_20181127133238-report' to D:\pk32_test\pk32\Ci\sv\out\ele_20181127133238-report.html
[main] INFO de.kosit.validationtool.cmd.SerializeReportAction - Serializing result to D:\pk32_test\pk32\Ci\sv\out\ele_20181127133238-report.xml
[main] INFO de.kosit.validationtool.impl.DefaultCheck - Finished check of in\ele_20181127133238.xml in 61406ms

[main] INFO de.kosit.validationtool.impl.DefaultCheck - Checking content of in\ele_20181127133656.xml
[main] INFO de.kosit.validationtool.cmd.ExtractHtmlContentAction - Writing report html 'ele_20181127133656-report' to D:\pk32_test\pk32\Ci\sv\out\ele_20181127133656-report.html
[main] INFO de.kosit.validationtool.cmd.SerializeReportAction - Serializing result to D:\pk32_test\pk32\Ci\sv\out\ele_20181127133656-report.xml
[main] INFO de.kosit.validationtool.impl.DefaultCheck - Finished check of in\ele_20181127133656.xml in 179329ms

[main] INFO de.kosit.validationtool.impl.DefaultCheck - Checking content of in\ele_20181127134111.xml
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
        at de.kosit.validationtool.impl.tasks.DocumentParseAction.parseDocument(DocumentParseAction.java:65)
        at de.kosit.validationtool.impl.tasks.DocumentParseAction.check(DocumentParseAction.java:83)
        at de.kosit.validationtool.impl.DefaultCheck.runCheckInternal(DefaultCheck.java:112)
        at de.kosit.validationtool.cmd.InternalCheck.lambda$checkInput$0(InternalCheck.java:61)
        at de.kosit.validationtool.cmd.InternalCheck$$Lambda$24/18230464.accept(Unknown Source)
        at java.util.ArrayList.forEach(Unknown Source)
        at de.kosit.validationtool.cmd.InternalCheck.checkInput(InternalCheck.java:59)
        at de.kosit.validationtool.cmd.CommandLineApplication.processActions(CommandLineApplication.java:155)
        at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:105)
        at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:85)

```

**Comment by rkottmann** [comment]
is there a chance that you can provide us with example input for reproducing the issue?

**Comment by fbuettner-hb** [comment]
The issue has been reported without the example input, as it contains personal data. So first step will be to reproduce it with dummy data. I am on it.

**Comment by fbuettner-hb** [comment]
To reproduce, extract the following files:

* https://github.com/itplr-kosit/validator/releases/download/validationtool-1_0_1/validationtool-dist-1.0.1-standalone.zip
* https://github.com/itplr-kosit/validator-configuration-xgewerbeanzeige/releases/download/release-2018-12-14/validator-configuration-xgewerbeanzeige_2018-12-14.zip
* [data.zip](https://github.com/itplr-kosit/validator/files/2828177/data.zip) into data/

Data contains 10 identical large sets.

And run `java -jar validationtool-1.0.1-standalone.jar -s scenarios.xml -h data/*.xml`

Output shows increasing runtimes for each data files, crashes on no. 4 on my machine.

**Comment by apenski** [comment]
the processing from the commandline now takes one file after another. Any intermediate result object will be dropped/removed from memory before the processing starts with next input file.

This is a first fix to the memory consumption behaviour. While analyzing this issue, we identified more things we can improve in future releases
