### ISSUE TITLE
Validator 1.1.0 throws NullPointerException when validating non-XML documents

### ISSUE THREAD

**Issue by MrMikeFloyd** [itplr-kosit/validator#37]
## Observed behaviour
When calling the validator's `checkInput()` method using a document that doesn't have a valid XML body (for instance, plain text), the method call will result in the validator crashing with a `java.lang.NullPointerException`.

## Expected behaviour
The validator does not throw an Exception but returns a `Result` object instead, indicating that the provided document does not contain valid/well-formed XML.

## Additional information

* validator version: 1.1.0
* Java version: 1.8

### Method call
validator is called as follows:
```
public void validate(byte[] documentToValidate) {
    Input document = InputFactory.read(documentToValidate, "xRechnung");
    lastResult = validator.checkInput(document);
}
```
### Test file content
The exception was encountered with any type of file content that did not contain any XML tags (a regular text file for instance).

### Stack trace
```
java.lang.NullPointerException
	at de.kosit.validationtool.impl.tasks.CreateReportAction.getTransformation(CreateReportAction.java:96)
	at de.kosit.validationtool.impl.tasks.CreateReportAction.check(CreateReportAction.java:76)
	at de.kosit.validationtool.impl.DefaultCheck.runCheckInternal(DefaultCheck.java:117)
	at de.kosit.validationtool.impl.DefaultCheck.checkInput(DefaultCheck.java:108)
```

## Validator log
```
INFO    2019-09-18 15:40:35,623 [main] de.kosit.validationtool.api.CheckConfiguration  - Creating default scenario repository (alongside scenario definition)
INFO    2019-09-18 15:40:35,724 [main] de.kosit.validationtool.impl.ScenarioRepository  - Loading scenarios from file:/xxxxxxxxxxxxx/target/classes/xRechnung_v120/scenarios.xml
INFO    2019-09-18 15:40:35,725 [main] de.kosit.validationtool.impl.ContentRepository  - Load schema from source file:/xxxxxxxxxxxxx/de/kosit/validationtool/1.1.0/validationtool-1.1.0.jar!/xsd/scenarios.xsd
INFO    2019-09-18 15:40:35,995 [main] de.kosit.validationtool.impl.ScenarioRepository  - Loaded scenarios for Prüftool-Konfiguration XRechnung 1.2.0 by KoSIT from 2018-12-19. The following scenarios are available:

EN16931 CIUS XRechnung (UBL Invoice)
EN16931 CIUS XRechnung (UBL CreditNote)
EN16931 CIUS XRechnung (CII)

INFO    2019-09-18 15:40:35,995 [main] de.kosit.validationtool.impl.ScenarioRepository  - Loading scenario content from file:/xxxxxxxxxxxxx/target/classes/xRechnung_v120/
INFO    2019-09-18 15:40:36,671 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
INFO    2019-09-18 15:40:37,803 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/xrechnung/1.2.0/xsl/XRechnung-UBL-validation-Invoice.xsl
INFO    2019-09-18 15:40:37,858 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/xrechnung-report.xsl
INFO    2019-09-18 15:40:38,075 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl
INFO    2019-09-18 15:40:38,869 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/xrechnung/1.2.0/xsl/XRechnung-UBL-validation-CreditNote.xsl
INFO    2019-09-18 15:40:38,907 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/xrechnung-report.xsl
INFO    2019-09-18 15:40:38,987 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/cii/16b/xsl/EN16931-CII-validation.xsl
INFO    2019-09-18 15:40:39,352 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/xrechnung/1.2.0/xsl/XRechnung-CII-validation.xsl
INFO    2019-09-18 15:40:39,376 [main] de.kosit.validationtool.impl.ContentRepository  - Loading XSLT script from  resources/xrechnung-report.xsl
INFO    2019-09-18 15:40:39,440 [main] de.kosit.validationtool.impl.DefaultCheck  - Checking content of xRechnung
INFO    2019-09-18 15:40:39,440 [main] de.kosit.validationtool.impl.DefaultCheck  - Step DefaultCheck$$Lambda$264/1295356732 finished in 0ms
Error on line 1 column 1 
  SXXP0003: Error reported by XML parser: Content ist nicht zulässig in Prolog.
INFO    2019-09-18 15:40:39,447 [main] de.kosit.validationtool.impl.tasks.DocumentParseAction  - Parsing war nicht erfolgreich: null -> [IOException while reading resource xRechnung: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog. At row null at pos null]
INFO    2019-09-18 15:40:39,448 [main] de.kosit.validationtool.impl.DefaultCheck  - Step DocumentParseAction finished in 8ms
INFO    2019-09-18 15:40:39,448 [main] de.kosit.validationtool.impl.DefaultCheck  - Step ScenarioSelectionAction finished in 0ms
INFO    2019-09-18 15:40:39,448 [main] de.kosit.validationtool.impl.DefaultCheck  - Step SchemaValidationAction finished in 0ms
INFO    2019-09-18 15:40:39,448 [main] de.kosit.validationtool.impl.DefaultCheck  - Step SchematronValidationAction finished in 0ms
INFO    2019-09-18 15:40:39,593 [main] de.kosit.validationtool.impl.DefaultCheck  - Step ValidateReportInputAction finished in 145ms
```

**Comment by JannickWeisshaupt** [comment]
This is honestly quite annoying and not at all minor.

**Comment by rkottmann** [comment]
Of course it might be annyoing. Minor label just means that a fix can be made in a minor new release. We are following Semnatic Versioning Scheme. We might even consider a patch release.

**Comment by apenski** [comment]
fixed in master, ready for release

**Comment by Cakmakli-a** [comment]
Der Fehler ist immer noch vorhanden in Version 1.3.0!
```
Error on line 1 column 1 of RechnungTest.pdf:
  SXXP0003: Error reported by XML parser: Content ist nicht zulässig in Prolog.
```
