### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by gperler** [itplr-kosit/validator#48]
I followed the instructions and got the following error
 java -jar validationtool-1.0.1-standalone.jar -s scenarios.xml  -h ubl.xml

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at de.kosit.validationtool.impl.DefaultCheck.<init>(DefaultCheck.java:73)
	at de.kosit.validationtool.cmd.InternalCheck.<init>(InternalCheck.java:48)
	at de.kosit.validationtool.cmd.CommandLineApplication.processActions(CommandLineApplication.java:135)
	at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:105)
	at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:85)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

My Java Version:
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by apenski** [comment]
version 1.0.1 is outdated and does not support java 9+ 
Please upgrade the validator or use java 8 (has jaxb bundled)
