### ISSUE TITLE
Nicht möglich eine `Configuration` zu erstellen

### ISSUE THREAD

**Issue by Cakmakli-a** [itplr-kosit/validator#67]
`final Conifuguration config = Configuration.load(URI.create("scenarios.xml")).resolvingMode(ResolvingMode.STRICT_LOCAL).build();`

Führt zu folgender Exception:
```
2020-11-16 18:01:29,091 [main] INFO  de.kosit.validationtool.config.ConfigurationLoader - Using resolving strategy STRICT_LOCAL

java.lang.SecurityException: class "net.sf.saxon.lib.Feature"'s signer information does not match signer information of other classes in the same package

	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.kosit.validationtool.impl.xml.StrictRelativeResolvingStrategy.createProcessor(StrictRelativeResolvingStrategy.java:106)
	at de.kosit.validationtool.impl.xml.BaseResolvingStrategy.getProcessor(BaseResolvingStrategy.java:52)
	at de.kosit.validationtool.config.ConfigurationLoader.build(ConfigurationLoader.java:136)
```

Konfigurationsdateien liegen local vor. Verstehe nicht, warum diese Exception geworfen wird.

**Comment by apenski** [comment]
Saxon-Jars sind an sich signiert. Für das Uber-Jar (*-standalone.jar) wird die signatur entfernt. 

Vermutung: entsprechend kann die nicht mehr geprüft werden. Standardmäßig sollte diese Prüfung deaktiviert sein (Java-Einstellung). Wenn die Prüfung bei Ihnen Pflicht ist, müssen auf das Uber-Jar verzichten und den Classpath selbst zusammenbauen. Alle nötigen Deps sind in der Distributation bzw. können auch aus der pom.xml herausgelesen werden

**Comment by Cakmakli-a** [comment]
Eine andere Möglichkeit wäre, die Dateien wie MANIFEST.MF, TE-050AC.RSA und TE-050AC.SF aus dem Ordner META-INF 
zu entfernen. Dann taucht dieses Problem nicht mehr auf. Ob das so "gut" ist, kann ich nicht einschätzen.

**Comment by apenski** [comment]
genau das meinte ich mit "signatur entfernt". Ich dachte eigentlich, dass das noch immer passiert, sehe aber, das in der java8-standalone die Datei TE-050AC.RSA noch drin ist, das ist so nicht gedacht

generell empfehle ich aber trotzdem bei Nutzung der API die Classpath selbst zusammenzustellen, da in dem Uber-jar auch nicht benutzte Artefakte für Commandline-Parsing etc. drin sind, die in diesem Anwendungsfall vermutlich nicht benötigt werden. Die Uber-jars sind eher für CLI-Nutzer gedacht

**Comment by Cakmakli-a** [comment]
Ist also die Validator-API direkt zu verwenden und nicht die "Standalone-Variante" "problematisch" !?

**Comment by apenski** [comment]
Weder noch! Wenn API dann bitte mit Maven oder Gradle o. ä. den Classpath selbst zusammenbauen. (wir liefern leider noch keine Version in Maven-Central aus, was das ganze etwas mühselig macht, ich hoffe das wir das ändern können, aktuell müssen wir aber mit der Situation leben).

Wenn CLI verwendet wird, dann können die Standalone-Jars (je nach JAVA-Version, wobei die validator-<version>-standalone.jar mit allen Version laufen sollte, halt nur mehr mitbringt als für java8 nötig wäre) verwendet werden. Wäre ja für eine CLI-Verwendung umständlich, wenn man sich erst den Classpath zusammenbauen müsste.

Die API zu verwenden ist definitiv ok. Konkreter Anwendungsfall wäre bspw. Integration der Funktkionalität in eine eigene Anwendung.
