### ISSUE TITLE
PDF/A3 validieren scheitert

### ISSUE THREAD

**Issue by Cakmakli-a** [itplr-kosit/validator#72]
Hallo,

eine XRechnung (2.0) mit dem Validator zu validieren funktioniert. XML wird nicht "beanstandet".
Eine PDF/A3 mit einer einbetteten XRechnung (2.0) zu validieren, endet mit folgender Exception:
```
2020-12-09 14:55:00,094 [main] INFO  de.kosit.validationtool.impl.DefaultCheck - Checking content of Invoice2020
Error on line 1 column 1 of Invoice2020:
  SXXP0003: Error reported by XML parser: Content ist nicht zulässig in Prolog.
2020-12-09 14:55:07,350 [main] DEBUG de.kosit.validationtool.impl.tasks.DocumentParseAction - Exception while parsing Invoice2020
net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; systemId: file:///C:/Projekte/zugferd/Invoice2020; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:360)
	at de.kosit.validationtool.impl.tasks.DocumentParseAction.parseDocument(DocumentParseAction.java:70)
	at de.kosit.validationtool.impl.tasks.DocumentParseAction.check(DocumentParseAction.java:90)
	at de.kosit.validationtool.impl.DefaultCheck.runCheckInternal(DefaultCheck.java:118)
	at de.kosit.validationtool.impl.DefaultCheck.checkInput(DefaultCheck.java:109)
	at de.euroimmun.server.validation.ConfigurableValidation.getResult(ConfigurableValidation.java:104)
	at de.euroimmun.server.validation.ConfigurableValidation.validate(ConfigurableValidation.java:65)
	at de.euroimmun.server.validation.ConfigurableValidationTest.testPDFValidation(ConfigurableValidationTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:///C:/Projekte/zugferd/Invoice2020; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:455)
	at net.sf.saxon.event.Sender.send(Sender.java:167)
	at net.sf.saxon.Configuration.buildDocumentTree(Configuration.java:4236)
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:357)
	... 32 more
Caused by: org.xml.sax.SAXParseException; systemId: file:///C:/Projekte/zugferd/Invoice2020; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:435)
	... 35 more
```

Bin leider noch nicht dahinter gekommen, was genau mit "Content ist nicht zulässig in Prolog." beanstandet wird.
Eine Idee was da genau beanstandet wird ???

**Comment by apenski** [comment]
das PDF direkt an den Validator zu geben wird nicht funktionieren - das wird momentan noch nicht unterstützt. Sie müssen das XML-Dokument selbst vorher extrahieren!

Wenn Sie die API des Validators nutzen, können Sie einen eigenen Extraktions-Schritt reinbauen. Das setzt aber Java-Programmierung voraus.

**Comment by jstaerk** [comment]
#38
