### ISSUE TITLE
incompatible with OpenJDK 16.0.1 on macOS

### ISSUE THREAD

**Issue by viegelinsch** [itplr-kosit/validator#84]
I try to run the validator according to the instruction given at https://github.com/itplr-kosit/validator-configuration-xrechnung#usage
on macOS 11.5.1 with OpenJDK

```shell
java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Homebrew (build 16.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.1+0, mixed mode, sharing)
```

```shell
java -jar validator/validationtool-1.4.2-java8-standalone.jar -s validator-configuration/scenarios.xml -h ubl.xml
```
results in

```
KoSIT Validator version 1.4.2
Loading scenarios from  file:///PATH/kosit/validator-configuration/scenarios.xml
Using repository  null
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
	at de.kosit.validationtool.api.Configuration.load(Configuration.java:113)
	at de.kosit.validationtool.cmd.Validator.getConfiguration(Validator.java:223)
	at de.kosit.validationtool.cmd.Validator.processActions(Validator.java:173)
	at de.kosit.validationtool.cmd.Validator.mainProgram(Validator.java:105)
	at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:92)
	at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:60)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationEventHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
```

And calling the other jar

```shell
java -jar validator/validationtool-1.4.2-standalone.jar -s validator-configuration/scenarios.xml -h ubl.xml
```
neither successful, because it results in

```
KoSIT Validator version 1.4.2
Loading scenarios from  file:///PATH/kosit/validator-configuration/scenarios.xml
Using repository  null
Aug. 12, 2021 3:14:51 PM com.sun.xml.bind.v2.runtime.reflect.opt.Injector <clinit>
SCHWERWIEGEND: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:558)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:166)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:51)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:157)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:255)
	at com.sun.xml.bind.v2.runtime.property.ArrayProperty.<init>(ArrayProperty.java:38)
	at com.sun.xml.bind.v2.runtime.property.ArrayERProperty.<init>(ArrayERProperty.java:58)
	at com.sun.xml.bind.v2.runtime.property.ArrayElementProperty.<init>(ArrayElementProperty.java:70)
	at com.sun.xml.bind.v2.runtime.property.ArrayElementNodeProperty.<init>(ArrayElementNodeProperty.java:32)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:493)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:310)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:144)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:268)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:171)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:129)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:307)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:478)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:435)
	at de.kosit.validationtool.impl.ConversionService.initialize(ConversionService.java:143)
	at de.kosit.validationtool.impl.ConversionService.initialize(ConversionService.java:133)
	at de.kosit.validationtool.impl.ConversionService.initialize(ConversionService.java:117)
	at de.kosit.validationtool.impl.ConversionService.getJaxbContext(ConversionService.java:89)
	at de.kosit.validationtool.impl.ConversionService.readXml(ConversionService.java:180)
	at de.kosit.validationtool.config.ConfigurationLoader.loadScenarios(ConfigurationLoader.java:171)
	at de.kosit.validationtool.config.ConfigurationLoader.build(ConfigurationLoader.java:139)
	at de.kosit.validationtool.cmd.Validator.processActions(Validator.java:173)
	at de.kosit.validationtool.cmd.Validator.mainProgram(Validator.java:105)
	at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:92)
	at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:60)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.lang.Class.getMethod(Class.java:2195)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:170)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:166)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	... 41 more

Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null

##############################
#     Validation failed!     #
##############################
```

Can anyone point me to a solution beside "Install ORACLE JAVA8!"?
Any help appreciated.

**Comment by viegelinsch** [comment]
And indeed, with ORACLE's java8 it works like a charm.

**Comment by apenski** [comment]
Maybe it's not a good idea to use a package for java 8 with a JDK >=11 
As documented in [packages](https://github.com/itplr-kosit/validator#packages) we provide a different jar for use with JDK>=11 which bundles JAXB. Up to java 8  this was part of the runtime.

Internally, we test the library with various jdk versions. See [pipeline definition](https://github.com/itplr-kosit/validator/blob/master/.gitlab-ci.yml). At least the versions used there are supported. So basically can use any openjdk distro. You don't need to install oracle jdk
